[Interface]
PrivateKey = 0MZ15enyChrrWDoS4gep5gFUcxRIeRenWjg0/DveUVg=
Address = 192.168.27.65/32
DNS = 212.27.38.253
MTU = 1360

[Peer]
PublicKey = x0NHc86cXBAzvdZPCjwQOWTIRCFYZuLxRZBib+bYZgg=
Endpoint = 81.56.18.67:48103
KeepAlive = 25

[Socks5]
BindAddress = 0.0.0.0:1080
